version: "3"

services: 
  app:
    container_name: "auth-be"
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      GO_WORK_DIR: "/github.com/wdhafin/eFishery-test"
      HTTP_HANDLER: "TRUE"
    restart: unless-stopped
