route:
  restricted: "restricted"
  public: "public"
auth:
  accessSecret: ""
  refreshSecret: ""
  accessExpiry: 15m # in minutes, default to 15 minutes
  refreshExpiry: 8760h # in hours, default to 6 months
